"""Sentiment

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1GsvBKaw8n-yXXeVUBG2_c5LPKyGjhKNN
"""

#pip install newspaper3k

#Import Libraries needed
from textblob import TextBlob
import nltk
from newspaper import Article
import pickle

#Get the article
#URL = 'https://everythingcomputerscience.com'

def sentiment(url):
  '''A function to get sentiment, given url of website as parameter'''
  article = Article(url)
  #NLP part
  #download the html content of the article
  article.download()
  #parse the article
  article.parse()
  #a one time download of punkt, for sentence tokenization
  nltk.download('punkt')
  #keyword extract
  article.nlp()

  #Summarizing document
  text = article.summary
  #print(text)

  #Printing sentiment value of summarized document
  obj = TextBlob(text)
  #display the sentiment of the document
  #by returning a value btw -0.1 and 1.0
  sentiment = obj.sentiment.polarity
  #print(sentiment)

  #Using strings to display the sentiment instead of numbers
  if sentiment == 0:
    sent = 'The text reviewed is neutral'
  elif sentiment < 0:
    sent = 'The text reviewed is negative'
  else:
    sent = 'The text reviewed is positive'
  return sent

#print(sentiment(URL))

#pickling the model
pickle.dump(sentiment, open('model.pkl', 'wb'))
